name: Gather Artifact Size for a Repo (Win)
run-name: Artifact sizes for ${{ github.repository_owner }}/${{ inputs.repository }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The repository in the current org to get a list of packages for
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    env:
      # Use the current org
      ORG: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.PAT }}
      REPO: ${{ inputs.repository }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |

          "Getting list of artifacts for the repo '$env:REPO' for org '$env:ORG'"
          "| Artifact | Size | URL |" > $env:GITHUB_STEP_SUMMARY
          "| ---- | ---- | ---- |" >> $env:GITHUB_STEP_SUMMARY
          $slug = "${env:ORG}/${env:REPO}"
          
          # Get the non-expired artifacts for the repo
          $artifacts = gh api repos/${slug}/actions/artifacts --paginate --jq '.artifacts[] | select(.expired == false)' | convertFrom-Json
          if( $artifacts.length ){
            foreach( $artifact in $artifacts ){
              $name, $size, $url = $artifact.name, $artifact.size_in_bytes, $artifact.url 
              "| $name | $size bytes | $url |" | tee -a $env:GITHUB_STEP_SUMMARY
            }
          }
