name: Delete Artifacts for a Repo
run-name: Delete artifacts for ${{ github.repository_owner }}/${{ inputs.repository }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The repository in the current org to delete artifacts for
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Use the current org
      ORG: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ secrets.PAT }}
      REPO: ${{ inputs.repository }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set +e
          echo "Getting list of artifacts for the repo \"${REPO}\" for org \"${ORG}\""

          export slug="${ORG}/${REPO}"
          
          # Get the non-expired artifacts for the repo
          artifacts=$(gh api repos/${slug}/actions/artifacts --paginate --jq '.artifacts[] | select(.expired == false)  | .id' | grep -v "Not Found")
          for artifact in $(echo artifacts); do
            echo "artifact ${artifact}"
            gh api -X DELETE /repos/${slug}/actions/artifacts/${artifact}
          done
